# Generated by Django 3.2.2 on 2021-05-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=50)),
                ('enum', models.IntegerField()),
                ('esal', models.IntegerField()),
                ('eadr', models.CharField(max_length=50)),
            ],
        ),
    ]
