# Generated by Django 2.2.5 on 2021-08-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('MobileNumber', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('adress', models.TextField(max_length=200)),
            ],
        ),
    ]
