# Generated by Django 2.2.5 on 2021-08-25 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='eadres',
            new_name='eaddr',
        ),
    ]
