# Generated by Django 3.2 on 2021-08-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=20)),
                ('enum', models.IntegerField()),
                ('eadres', models.CharField(max_length=20)),
                ('esal', models.IntegerField()),
            ],
        ),
    ]
